#! /bin/sh

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo "The top level directory of the project is: " $SCRIPT_DIR

# source top level directory
export TOP_LEVEL_DIR=${SCRIPT_DIR}

# target dirs
mkdir -p ${TOP_LEVEL_DIR}/lib64
mkdir -p ${TOP_LEVEL_DIR}/bin

# set library path, so we can run our test binaries
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TOP_LEVEL_DIR}/lib64

# obj dirs
mkdir -p ${TOP_LEVEL_DIR}/src/obj
mkdir -p ${TOP_LEVEL_DIR}/test/obj
